### ISSUE TITLE
Clicking on a video title close current playing video

### ISSUE THREAD

**Issue by borisrorsvort** [Ralex86/Tunesbook#3]
It should replace current playing video and not toggle the panel if there is another video playing

**Comment by Ralex86** [comment]
![screen shot 2017-09-05 at 17 39 01](https://user-images.githubusercontent.com/24508644/30070210-06c209ea-9263-11e7-9a53-7b541d1fb22c.png)
I've been working on some small details lately on your advices... Don't have much time as I went back to engineer school this monday. Feel free to dig into the code and change whatever you want. I'll check time to time this project and try to solve the issues you opened ! Again thx
