### ISSUE TITLE
It's not clear how to play current video from the panel

### ISSUE THREAD

**Issue by borisrorsvort** [Ralex86/Tunesbook#4]
![selection_037](https://user-images.githubusercontent.com/39081/28635995-0002c284-723d-11e7-9b35-5361fb786653.jpg)
I suggest to add some «play» icon next to the title or something. 
The call to action button is a bit too much. Maybe useful as such only when there is no video submission yet

**Comment by Ralex86** [comment]
Yeah I know this button is ugly. I'll fix that
