### ISSUE TITLE
Current tune type input placeholder is wrong

### ISSUE THREAD

**Issue by borisrorsvort** [Ralex86/Tunesbook#5]
When you select another type of tune, the input placeholder doesn't change accordingly.
This is confusing. Also the dropdown doesn't show which type is selected as well
![selection_038](https://user-images.githubusercontent.com/39081/28636202-b09f031e-723d-11e7-91a6-596cbc216a86.jpg)

**Comment by Ralex86** [comment]
Ok I've just noticed today that you added some issues. I will read them carefully and see what I can do ! Thanks !
